[config.wallpaper]
command = 'swww'
arguments = ['img', '--transition-step', '10']
set = true

[templates.mako]
input_path = './templates/mako.ini'
output_path = '~/.config/mako/colors.ini'
post_hook = 'makoctl reload'

[templates.nvim]
input_path = './templates/nvim_mini_hues.lua'
output_path = '~/.config/nvim/plugin/99_mini_hues.lua'
post_hook = 'pkill -SIGUSR1 nvim'

[templates.river]
input_path = './templates/river'
output_path = '~/.config/river/colors'
post_hook = '~/.config/river/colors'

[templates.rofi]
input_path = './templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.zathura]
input_path = './templates/zathura-colors'
output_path = '~/.config/zathura/colors'
